/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastane_otomasyon;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author gokan
 */
public class Teşhis extends javax.swing.JFrame {

    public class ornekprivate
    
    {
    private String ornek;
    
    public String getOrnek()
    {
        return this.ornek;
    
    }
    public void  setOrnek(String ornek1)
    {
            this.ornek = ornek1;
    
    };
    
    
    }
    
    
    
    
    public class InnerClassOrnek1
    {
       
        public InnerClassOrnek1()
       {
            System.out.println("innerClass1  fonksiyonu çalıştı ve ekleme işlemi tamamlandı");
        
       }
        public class InnerClassOrnek2
        {
        public InnerClassOrnek2()
       {
            System.out.println("innerClass2  fonksiyonu çalıştı ve ekleme işlemi tamamlandı");
        
       }
        }
    }
    public Teşhis() {
        
        initComponents();
        GetHasta();
       // Selectional();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TeshisId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PatAdı = new javax.swing.JTextField();
        PatId = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Belirtiler = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        İlaçlar = new javax.swing.JTextField();
        Teşhis = new javax.swing.JTextField();
        Sonuc = new javax.swing.JTextField();
        TeshisEkle = new javax.swing.JButton();
        TeshisSil = new javax.swing.JButton();
        Guncelle = new javax.swing.JButton();
        Temizle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeshisTablosu = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        AnaMenu = new javax.swing.JButton();
        YazdırBtn = new javax.swing.JButton();
        Listele = new javax.swing.JButton();
        Ara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 48)); // NOI18N
        jLabel1.setText("HASTANE OTOMASYONU");

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        jLabel2.setText("TEŞHİS İŞLEMLERİ");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel6.setText("AD");

        TeshisId.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel3.setText("PATID");

        PatAdı.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N

        PatId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatIdActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel7.setText("BELİRTİLER");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel8.setText("İLAÇLAR");

        Belirtiler.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel4.setText("TEŞHİS");

        İlaçlar.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N

        Teşhis.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N

        TeshisEkle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TeshisEkle.setText("EKLE");
        TeshisEkle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeshisEkleMouseClicked(evt);
            }
        });

        TeshisSil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TeshisSil.setText("SİL");
        TeshisSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeshisSilActionPerformed(evt);
            }
        });

        Guncelle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Guncelle.setText("GÜNCELLE");
        Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuncelleActionPerformed(evt);
            }
        });

        Temizle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Temizle.setText("TEMİZLE");
        Temizle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TemizleMouseClicked(evt);
            }
        });

        TeshisTablosu.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        TeshisTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEŞHISID", "HASTAID", "HASTAADI", "BELİRTİLER", "TEŞHİS", "İLAÇLAR"
            }
        ));
        TeshisTablosu.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TeshisTablosu.setRowHeight(32);
        TeshisTablosu.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TeshisTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeshisTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TeshisTablosu);

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel9.setText("TEŞHİS LİSTESİ");

        AnaMenu.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        AnaMenu.setText("ANA MENÜ");
        AnaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaMenuActionPerformed(evt);
            }
        });

        YazdırBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        YazdırBtn.setText("YAZDIR");
        YazdırBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YazdırBtnActionPerformed(evt);
            }
        });

        Listele.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Listele.setText("LİSTELE");
        Listele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeleActionPerformed(evt);
            }
        });

        Ara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ara.setText("Ara");
        Ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PatAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TeshisId, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(PatId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(İlaçlar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Belirtiler, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Teşhis, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(Sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(YazdırBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Listele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AnaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(427, 427, 427))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(TeshisEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeshisSil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(TeshisId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PatAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(PatId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(45, 45, 45))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Belirtiler, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(Teşhis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel8))
                                    .addComponent(İlaçlar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Sonuc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeshisEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeshisSil, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(YazdırBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Listele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ara)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
interface ListeleAra
{

    void Listele();
    void Ara();
}
    interface SonucYazdır
    {
        void Yazdır();
    
    }
    interface TeshisCrud extends SonucYazdır
   
    {
      
      void TeshisEkle();
      void TeshisSil();
      void TeshisGuncelle();
    }
    static Connection Con =null;
    static Statement St =null;
    static ResultSet Rs=null,Rs1=null;
    private void GetHasta()
    {
        try
        {
            Con=DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneOtomasyonu","kullanici1","1234");
        St=Con.createStatement();
        String Query="select * from HASTALAR";
        Rs=St.executeQuery(Query);
        while(Rs.next()){
        String hastano=Rs.getString("HASTAID");
        PatId.addItem(hastano);
            
            
        }
        }
        catch(Exception e)
        {
        
        }
        
        
        
    
    }
    
    private void GetHastaAdı()
    {
        try
        {
            Con=DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneOtomasyonu","kullanici1","1234");
            St=Con.createStatement();
            String Query="select * from HASTALAR where HASTAID="+PatId.getSelectedItem().toString()+"";
            Rs1=St.executeQuery(Query);
            while(Rs1.next()){
            String hastaadı=Rs1.getString("HASTAADI");
            PatAdı.setText(hastaadı);
        }
            
        
        }
        catch(Exception e)
        {
        
        }
        
        
        
    
    }
    
    
    
    
    private void Selectional()
{
    
    try
    {
    Con=DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneOtomasyonu","kullanici1","1234");
    St=Con.createStatement();
    Rs=St.executeQuery("select * from TEŞHIS");
    TeshisTablosu.setModel(DbUtils.resultSetToTableModel(Rs));
    
    }
    catch(Exception e)
            {
            e.printStackTrace();
            }
}
    public class TeshisIslemler implements TeshisCrud,ListeleAra{

        
        TeshisIslemler()
                {
                    System.out.println("yapıcı fonksiyon çalıştı");
                }
        @Override
        public void TeshisEkle() 
        {
            try
        
        {
            
        Con=DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneOtomasyonu","kullanici1","1234");
        PreparedStatement Ekle =Con.prepareStatement("insert into TEŞHIS values(?,?,?,?,?,?)");
        Ekle.setInt(1,Integer.valueOf(TeshisId.getText()));
        Ekle.setInt(2,Integer.valueOf(PatId.getSelectedItem().toString()));
        Ekle.setString(3,PatAdı.getText());
        Ekle.setString(4,Belirtiler.getText());
        Ekle.setString(5,Teşhis.getText());
        Ekle.setString(6,İlaçlar.getText());
        int row =Ekle.executeUpdate();
     //  JOptionPane.showMessageDialog(this,"Teşhis Başarı ile Eklendi");
        Con.close();
        Selectional();
        
        }
        catch(Exception e )
        {
            e.printStackTrace();
        }
        }

        @Override
        public void TeshisSil()
        
        {
            try{
        Con=DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneOtomasyonu","kullanici1","1234");
        String Id=TeshisId.getText();
        String Query="Delete from TEŞHIS where TEŞHISID="+Id;
        Statement Ekle=Con.createStatement();
        Ekle.executeUpdate(Query);
        Selectional();
      //  JOptionPane.showMessageDialog(this, "Teşhis başarı ile silindi");
        }
        catch(Exception e)
                {
                    e.printStackTrace();
                }
            
            
        }

        @Override
        public void TeshisGuncelle() 
        {
         try
            {
                Con=DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneOtomasyonu","kullanici1","1234");
                             String Query="Update TEŞHIS set BELIRTILER='"+Belirtiler.getText()+"'"+",TEŞHIS='"+Teşhis.getText()+"'"+",İLAÇLAR='"+İlaçlar.getText()+"' where TEŞHISID="+TeshisId.getText();
                System.out.println(Query);
                Statement Ekle=Con.createStatement();
                Ekle.executeUpdate(Query);
                Ara();                
            
            }
            catch(Exception e)
            {
            e.printStackTrace(); 
            }
            
            
            
        }

        @Override
        public void Yazdır() {
            try
            {
                Sonuc.print();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }

        @Override
        public void Listele() {
             try
    {
    Con=DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneOtomasyonu","kullanici1","1234");
    St=Con.createStatement();
    Rs=St.executeQuery("select * from TEŞHIS");
    TeshisTablosu.setModel(DbUtils.resultSetToTableModel(Rs));
    
    }
    catch(Exception e)
            {
            e.printStackTrace();
            }
        }

        @Override
        public void Ara() {
            try{
        Con=DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneOtomasyonu","kullanici1","1234");
        St=Con.createStatement();
    Rs=St.executeQuery("select * from TEŞHIS where TEŞHISID= "+TeshisId.getText());
    TeshisTablosu.setModel(DbUtils.resultSetToTableModel(Rs));
       
      //  JOptionPane.showMessageDialog(this, "Teşhis başarı ile bulundu");
        }
        catch(Exception e)
                {
                    e.printStackTrace();
                }
        }
    
    }
    
    
    private void TeshisEkleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeshisEkleMouseClicked
       TeshisIslemler ti=new TeshisIslemler();
       ti.TeshisEkle();
       InnerClassOrnek1 ıco=new InnerClassOrnek1();
       
       
       
    }//GEN-LAST:event_TeshisEkleMouseClicked

    private void PatIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatIdActionPerformed
        GetHastaAdı();
    }//GEN-LAST:event_PatIdActionPerformed

    private void TeshisSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeshisSilActionPerformed
        TeshisIslemler ti=new TeshisIslemler();
       ti.TeshisSil();
    }//GEN-LAST:event_TeshisSilActionPerformed

    private void TemizleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TemizleMouseClicked
       TeshisId.setText("");
       Belirtiler.setText("");
       Teşhis.setText("");
       İlaçlar.setText("");
       Sonuc.setText("");
       PatAdı.setText("");
       
       
    }//GEN-LAST:event_TemizleMouseClicked

    private void GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuncelleActionPerformed
       TeshisIslemler ti=new TeshisIslemler();
       ti.TeshisGuncelle();
    }//GEN-LAST:event_GuncelleActionPerformed

    private void TeshisTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeshisTablosuMouseClicked
       DefaultTableModel model=(DefaultTableModel)TeshisTablosu.getModel();
       int myindex=TeshisTablosu.getSelectedRow();
       String hastaadı=model.getValueAt(myindex,2).toString();
       String belirtiler=model.getValueAt(myindex,3).toString();
       String teshis=model.getValueAt(myindex,4).toString();
       String ilaç=model.getValueAt(myindex,5).toString();
       Sonuc.setText(Sonuc.getText()+"\n\n"+"    :Hasta Adı"+hastaadı+"     "+"Belirtiler:"+belirtiler+"\n\nTeşhis:"+teshis+"    İlaçlar"+ilaç);
    }//GEN-LAST:event_TeshisTablosuMouseClicked

    private void YazdırBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YazdırBtnActionPerformed
       TeshisIslemler ti=new TeshisIslemler();
       ti.Yazdır();
    }//GEN-LAST:event_YazdırBtnActionPerformed

    private void AnaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaMenuActionPerformed
        new AnaForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AnaMenuActionPerformed

    private void ListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeleActionPerformed
        TeshisIslemler ti=new TeshisIslemler();
       ti.Listele();
    }//GEN-LAST:event_ListeleActionPerformed

    private void AraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AraActionPerformed
       TeshisIslemler ti=new TeshisIslemler();
       ti.Ara();
    }//GEN-LAST:event_AraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teşhis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teşhis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teşhis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teşhis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teşhis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnaMenu;
    private javax.swing.JButton Ara;
    private javax.swing.JTextField Belirtiler;
    private javax.swing.JButton Guncelle;
    private javax.swing.JButton Listele;
    private javax.swing.JTextField PatAdı;
    private javax.swing.JComboBox PatId;
    private javax.swing.JTextField Sonuc;
    private javax.swing.JButton Temizle;
    private javax.swing.JButton TeshisEkle;
    private javax.swing.JTextField TeshisId;
    private javax.swing.JButton TeshisSil;
    private javax.swing.JTable TeshisTablosu;
    private javax.swing.JTextField Teşhis;
    private javax.swing.JButton YazdırBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField İlaçlar;
    // End of variables declaration//GEN-END:variables
}
